// Seed data for the study platform
// Run with: npx ts-node --compiler-options '{"module":"commonjs"}' src/lib/seed.ts

export const subjectsData = [
  // Matemática
  {
    name: "Matemática",
    slug: "matematica",
    color: "#6C63FF",
    icon: "Calculator",
    area: "matematica",
    order: 1,
    topics: [
      {
        name: "Fundamentos da Matemática",
        slug: "fundamentos",
        description: "Frações, MMC, MDC, potenciação e radiciação",
        subtopics: ["Frações", "MMC e MDC", "Potenciação e Radiciação", "Notação Científica", "Unidades de Medida"],
      },
      {
        name: "Razão, Proporção e Regra de 3",
        slug: "razao-proporcao",
        description: "Grandezas proporcionais e regra de três",
        subtopics: ["Razão e Proporção", "Regra de 3 Simples", "Regra de 3 Composta"],
      },
      {
        name: "Porcentagem e Matemática Financeira",
        slug: "porcentagem-financeira",
        description: "Descontos, juros simples e compostos",
        subtopics: ["Porcentagem", "Juros Simples", "Juros Compostos", "Parcelamentos"],
      },
      {
        name: "Estatística",
        slug: "estatistica",
        description: "Média, mediana, moda e desvio padrão",
        subtopics: ["Média Aritmética", "Mediana e Moda", "Desvio Padrão", "Gráficos e Tabelas"],
      },
      {
        name: "Funções",
        slug: "funcoes",
        description: "Funções do 1° e 2° grau, exponencial e logarítmica",
        subtopics: ["Função do 1° Grau", "Função do 2° Grau", "Progressão Aritmética", "Progressão Geométrica", "Função Exponencial", "Função Logarítmica"],
      },
      {
        name: "Geometria Plana",
        slug: "geometria-plana",
        description: "Áreas, perímetros e relações geométricas",
        subtopics: ["Triângulos", "Quadriláteros", "Círculos", "Polígonos Regulares"],
      },
      {
        name: "Trigonometria",
        slug: "trigonometria",
        description: "Seno, cosseno, tangente e funções trigonométricas",
        subtopics: ["Razões Trigonométricas", "Ciclo Trigonométrico", "Funções Trigonométricas"],
      },
      {
        name: "Geometria Espacial",
        slug: "geometria-espacial",
        description: "Prismas, pirâmides, cones, cilindros e esferas",
        subtopics: ["Prismas e Cilindros", "Pirâmides e Cones", "Esferas", "Projeção Ortogonal"],
      },
      {
        name: "Análise Combinatória e Probabilidade",
        slug: "combinatoria-probabilidade",
        description: "Permutações, combinações e probabilidade",
        subtopics: ["Princípio Fundamental", "Permutações", "Combinações", "Probabilidade"],
      },
      {
        name: "Álgebra e Matrizes",
        slug: "algebra-matrizes",
        description: "Sistemas, conjuntos, matrizes e geometria analítica",
        subtopics: ["Conjuntos", "Sistemas Lineares", "Matrizes e Determinantes", "Geometria Analítica"],
      },
    ],
    videos: [
      { title: "TABUADA para MEDICINA e ENEM (método incrível)", channel: "Pedro Assaad", duration: "45:20", url: "https://youtube.com" },
      { title: "PORCENTAGEM para ENEM MEDICINA (vire uma máquina)", channel: "Pedro Assaad", duration: "38:15", url: "https://youtube.com" },
      { title: "Fundamentos básicos da Matemática Financeira", channel: "Pedro Assaad", duration: "42:30", url: "https://youtube.com" },
      { title: "TUDO de SISTEMAS para o ENEM 2026", channel: "Pedro Assaad", duration: "55:00", url: "https://youtube.com" },
      { title: "Tudo de ESCALAS para o ENEM 2026", channel: "Pedro Assaad", duration: "30:10", url: "https://youtube.com" },
      { title: "TUDO de ANÁLISE COMBINATÓRIA em apenas 1 hora", channel: "Pedro Assaad", duration: "1:02:45", url: "https://youtube.com" },
      { title: "TODA A MATEMÁTICA DO ENEM EM 12 HORAS", channel: "Pedro Assaad", duration: "12:00:00", url: "https://youtube.com" },
      { title: "TUDO de Matemática do Ensino FUNDAMENTAL", channel: "Pedro Assaad", duration: "3:45:00", url: "https://youtube.com" },
      { title: "Matemática Básica - Curso Completo", channel: "Ferretto Matemática", duration: "2:30:00", url: "https://youtube.com" },
      { title: "Função do 2° Grau - Aula Completa", channel: "Me Salva!", duration: "45:00", url: "https://youtube.com" },
    ],
  },
  // Física
  {
    name: "Física",
    slug: "fisica",
    color: "#00D4FF",
    icon: "Atom",
    area: "natureza",
    order: 2,
    topics: [
      { name: "Energia e Transformações", slug: "energia", description: "Conservação de energia, cinética e potencial", subtopics: ["Energia Cinética", "Energia Potencial", "Conservação de Energia"] },
      { name: "Ondulatória", slug: "ondulatoria", description: "Frequência, comprimento de onda, som e luz", subtopics: ["Ondas Mecânicas", "Som", "Luz e Espectro"] },
      { name: "Termologia", slug: "termologia", description: "Calor, temperatura, dilatação e termodinâmica", subtopics: ["Calorimetria", "Dilatação", "Termodinâmica", "Gases"] },
      { name: "Cinemática", slug: "cinematica", description: "MRU, MRUV, queda livre e lançamentos", subtopics: ["MRU", "MRUV", "Queda Livre", "Vetores"] },
      { name: "Dinâmica", slug: "dinamica", description: "Leis de Newton, forças e equilíbrio", subtopics: ["1ª Lei de Newton", "2ª Lei de Newton", "3ª Lei de Newton", "Força de Atrito", "Trabalho e Energia"] },
      { name: "Eletricidade", slug: "eletricidade", description: "Eletrostática, corrente e circuitos", subtopics: ["Eletrostática", "Lei de Ohm", "Circuitos Elétricos", "Potência Elétrica"] },
      { name: "Óptica", slug: "optica", description: "Reflexão, refração, espelhos e lentes", subtopics: ["Reflexão", "Refração", "Espelhos", "Lentes"] },
      { name: "Magnetismo e Eletromagnetismo", slug: "magnetismo", description: "Campo magnético, indução e transformadores", subtopics: ["Campo Magnético", "Força Magnética", "Indução Eletromagnética"] },
      { name: "Hidrostática", slug: "hidrostatica", description: "Pressão, empuxo e princípios de fluidos", subtopics: ["Pressão", "Empuxo", "Princípio de Pascal", "Princípio de Arquimedes"] },
      { name: "Gravitação", slug: "gravitacao", description: "Lei da gravitação universal e leis de Kepler", subtopics: ["Gravitação Universal", "Leis de Kepler", "Movimentos Orbitais"] },
    ],
    videos: [
      { title: "LEIS DE NEWTON - porém irá mudar a sua vida", channel: "Pedro Assaad", duration: "48:30", url: "https://youtube.com" },
      { title: "Revisão de Termologia ENEM 2026", channel: "Pedro Assaad", duration: "55:00", url: "https://youtube.com" },
      { title: "Curso completo de CINEMÁTICA pro ENEM 2026", channel: "Pedro Assaad", duration: "1:30:00", url: "https://youtube.com" },
      { title: "Fundamentos de ELETRODINÂMICA pro ENEM", channel: "Pedro Assaad", duration: "42:00", url: "https://youtube.com" },
      { title: "Eletrostática para o ENEM 2026", channel: "Pedro Assaad", duration: "35:00", url: "https://youtube.com" },
      { title: "Óptica geométrica para o ENEM 2026", channel: "Pedro Assaad", duration: "40:00", url: "https://youtube.com" },
      { title: "REFRAÇÃO em nível avançado para o ENEM 2026", channel: "Pedro Assaad", duration: "38:00", url: "https://youtube.com" },
      { title: "TUDO de ELETROMAGNETISMO para o ENEM 2026", channel: "Pedro Assaad", duration: "1:15:00", url: "https://youtube.com" },
      { title: "TODA A FÍSICA DO ENEM 2026 em 12 horas", channel: "Pedro Assaad", duration: "12:00:00", url: "https://youtube.com" },
      { title: "Física do ENEM - Exercícios Resolvidos", channel: "Me Salva!", duration: "2:00:00", url: "https://youtube.com" },
    ],
  },
  // Química
  {
    name: "Química",
    slug: "quimica",
    color: "#FF6584",
    icon: "FlaskConical",
    area: "natureza",
    order: 3,
    topics: [
      { name: "Propriedades da Matéria", slug: "propriedades-materia", description: "Estados físicos, densidade e transformações", subtopics: ["Estados da Matéria", "Densidade", "Mudanças de Estado"] },
      { name: "Atomística e Tabela Periódica", slug: "atomistica", description: "Modelos atômicos, elementos e propriedades periódicas", subtopics: ["Modelos Atômicos", "Tabela Periódica", "Propriedades Periódicas"] },
      { name: "Ligações Químicas", slug: "ligacoes", description: "Iônica, covalente, metálica e forças intermoleculares", subtopics: ["Ligação Iônica", "Ligação Covalente", "Geometria Molecular", "Polaridade"] },
      { name: "Química Inorgânica", slug: "inorganica", description: "Ácidos, bases, sais e óxidos", subtopics: ["Ácidos", "Bases", "Sais", "Óxidos", "Reações Inorgânicas"] },
      { name: "Estequiometria", slug: "estequiometria", description: "Cálculos com reagentes e produtos", subtopics: ["Balanceamento", "Mol e Massa Molar", "Cálculos Estequiométricos", "Rendimento"] },
      { name: "Soluções e Propriedades Coligativas", slug: "solucoes", description: "Concentração, diluição e propriedades", subtopics: ["Concentração", "Diluição", "Propriedades Coligativas"] },
      { name: "Termoquímica e Cinética", slug: "termoquimica-cinetica", description: "Entalpia, velocidade de reação e catalisadores", subtopics: ["Entalpia", "Lei de Hess", "Velocidade de Reação", "Catalisadores"] },
      { name: "Equilíbrio Químico", slug: "equilibrio", description: "Constante de equilíbrio, pH e Le Chatelier", subtopics: ["Constante de Equilíbrio", "Le Chatelier", "pH e pOH", "Hidrólise"] },
      { name: "Eletroquímica e Radioatividade", slug: "eletroquimica", description: "Pilhas, eletrólise e decaimento radioativo", subtopics: ["Pilhas", "Eletrólise", "Radioatividade", "Meia-Vida"] },
      { name: "Química Orgânica", slug: "organica", description: "Cadeias carbônicas, funções e reações orgânicas", subtopics: ["Cadeias Carbônicas", "Funções Orgânicas", "Isomeria", "Reações Orgânicas", "Polímeros"] },
    ],
    videos: [
      { title: "Você REALMENTE sabe o que é MOL?", channel: "Pedro Assaad", duration: "30:00", url: "https://youtube.com" },
      { title: "Tudo de Estequiometria para o ENEM 2026", channel: "Pedro Assaad", duration: "1:20:00", url: "https://youtube.com" },
      { title: "Química Orgânica - Funções", channel: "Descomplica", duration: "45:00", url: "https://youtube.com" },
      { title: "Ligações Químicas Completo", channel: "Me Salva!", duration: "50:00", url: "https://youtube.com" },
      { title: "Tabela Periódica - Tudo que você precisa", channel: "Stoodi", duration: "35:00", url: "https://youtube.com" },
      { title: "Equilíbrio Químico ENEM", channel: "Descomplica", duration: "40:00", url: "https://youtube.com" },
      { title: "Eletroquímica para ENEM", channel: "Me Salva!", duration: "55:00", url: "https://youtube.com" },
      { title: "Termoquímica Completa", channel: "Stoodi", duration: "48:00", url: "https://youtube.com" },
      { title: "Radioatividade Descomplicada", channel: "Descomplica", duration: "30:00", url: "https://youtube.com" },
      { title: "Toda a Química Orgânica", channel: "Me Salva!", duration: "2:00:00", url: "https://youtube.com" },
    ],
  },
  // Biologia
  {
    name: "Biologia",
    slug: "biologia",
    color: "#00E676",
    icon: "Dna",
    area: "natureza",
    order: 4,
    topics: [
      { name: "Citologia e Moléculas da Vida", slug: "citologia", description: "Célula, organelas, membrana e biomoléculas", subtopics: ["Membrana Plasmática", "Organelas", "Biomoléculas", "Transportes Celulares"] },
      { name: "Metabolismo Energético", slug: "metabolismo", description: "Fotossíntese, respiração e fermentação", subtopics: ["Fotossíntese", "Respiração Celular", "Fermentação"] },
      { name: "Biologia Molecular e Biotecnologia", slug: "biologia-molecular", description: "DNA, RNA, síntese proteica e engenharia genética", subtopics: ["DNA e RNA", "Síntese Proteica", "Engenharia Genética", "Mutações"] },
      { name: "Genética", slug: "genetica", description: "Leis de Mendel, herança e probabilidade", subtopics: ["1ª Lei de Mendel", "2ª Lei de Mendel", "Codominância", "Herança Ligada ao Sexo"] },
      { name: "Evolução", slug: "evolucao", description: "Seleção natural, adaptação e especiação", subtopics: ["Darwinismo", "Lamarckismo", "Seleção Natural", "Especiação"] },
      { name: "Ecologia", slug: "ecologia", description: "Relações ecológicas, cadeias e ciclos", subtopics: ["Cadeias Alimentares", "Relações Ecológicas", "Ciclos Biogeoquímicos", "Biomas"] },
      { name: "Fisiologia Humana", slug: "fisiologia", description: "Sistemas do corpo humano", subtopics: ["Sistema Digestório", "Sistema Circulatório", "Sistema Nervoso", "Sistema Endócrino", "Sistema Imunológico"] },
      { name: "Botânica", slug: "botanica", description: "Classificação, fisiologia e reprodução vegetal", subtopics: ["Grupos Vegetais", "Fisiologia Vegetal", "Reprodução", "Hormônios Vegetais"] },
      { name: "Doenças e Saúde Pública", slug: "doencas", description: "Patologias, vacinação e saneamento", subtopics: ["Doenças Bacterianas", "Doenças Virais", "Parasitoses", "Vacinação"] },
      { name: "Classificação dos Seres Vivos", slug: "taxonomia", description: "Reinos, filos e diversidade biológica", subtopics: ["Vírus", "Bactérias", "Protistas", "Fungos", "Animais"] },
    ],
    videos: [
      { title: "TUDO DE CITOLOGIA PARA O ENEM 2026", channel: "Pedro Assaad", duration: "1:10:00", url: "https://youtube.com" },
      { title: "Sistema Digestório para o ENEM 2026", channel: "Pedro Assaad", duration: "45:00", url: "https://youtube.com" },
      { title: "Introdução ao Sistema Endócrino", channel: "Pedro Assaad", duration: "38:00", url: "https://youtube.com" },
      { title: "Lamarckismo x Darwinismo ENEM 2026", channel: "Pedro Assaad", duration: "32:00", url: "https://youtube.com" },
      { title: "Fermentação Alcoólica pro ENEM 2026", channel: "Pedro Assaad", duration: "28:00", url: "https://youtube.com" },
      { title: "TUDO de BOTÂNICA para o ENEM 2026", channel: "Pedro Assaad", duration: "1:30:00", url: "https://youtube.com" },
      { title: "TUDO de GENÉTICA para o ENEM 2026", channel: "Pedro Assaad", duration: "1:45:00", url: "https://youtube.com" },
      { title: "Hormônios Femininos e Ciclo Menstrual", channel: "Pedro Assaad", duration: "40:00", url: "https://youtube.com" },
      { title: "Ecologia para ENEM - Completo", channel: "Descomplica", duration: "1:20:00", url: "https://youtube.com" },
      { title: "Biologia Celular - Curso Completo", channel: "Me Salva!", duration: "2:30:00", url: "https://youtube.com" },
    ],
  },
  // Português
  {
    name: "Língua Portuguesa",
    slug: "portugues",
    color: "#FF9100",
    icon: "BookOpen",
    area: "linguagens",
    order: 5,
    topics: [
      { name: "Funções da Linguagem", slug: "funcoes-linguagem", description: "Emotiva, referencial, conativa, fática, metalinguística e poética", subtopics: ["Função Emotiva", "Função Referencial", "Função Conativa", "Função Poética"] },
      { name: "Figuras de Linguagem", slug: "figuras-linguagem", description: "Metáfora, ironia, hipérbole e outras", subtopics: ["Metáfora", "Metonímia", "Ironia", "Hipérbole", "Antítese"] },
      { name: "Gêneros Textuais", slug: "generos-textuais", description: "Tipos e gêneros textuais e suas funções", subtopics: ["Narração", "Dissertação", "Descrição", "Gêneros Digitais"] },
      { name: "Literatura Brasileira", slug: "literatura", description: "Movimentos literários do Brasil", subtopics: ["Barroco", "Arcadismo", "Romantismo", "Realismo/Naturalismo", "Modernismo"] },
      { name: "Interpretação de Texto", slug: "interpretacao", description: "Estratégias de leitura e compreensão", subtopics: ["Inferência", "Intertextualidade", "Coesão e Coerência"] },
    ],
    videos: [
      { title: "Funções da Linguagem - Completo", channel: "Professor Noslen", duration: "25:00", url: "https://youtube.com" },
      { title: "Figuras de Linguagem ENEM", channel: "Professor Noslen", duration: "30:00", url: "https://youtube.com" },
      { title: "Literatura Brasileira - Revisão Completa", channel: "Descomplica", duration: "1:30:00", url: "https://youtube.com" },
      { title: "Interpretação de Textos ENEM", channel: "Professor Noslen", duration: "40:00", url: "https://youtube.com" },
      { title: "Gêneros Textuais para ENEM", channel: "Stoodi", duration: "35:00", url: "https://youtube.com" },
      { title: "Gramática Essencial ENEM", channel: "Professor Noslen", duration: "2:00:00", url: "https://youtube.com" },
      { title: "Modernismo Brasileiro Completo", channel: "Descomplica", duration: "45:00", url: "https://youtube.com" },
      { title: "Coesão e Coerência Textual", channel: "Me Salva!", duration: "28:00", url: "https://youtube.com" },
      { title: "Romantismo no Brasil", channel: "Professor Noslen", duration: "32:00", url: "https://youtube.com" },
      { title: "Variação Linguística ENEM", channel: "Stoodi", duration: "20:00", url: "https://youtube.com" },
    ],
  },
  // História
  {
    name: "História",
    slug: "historia",
    color: "#FFD600",
    icon: "Landmark",
    area: "humanas",
    order: 6,
    topics: [
      { name: "Idade Antiga", slug: "idade-antiga", description: "Grécia, Roma, cidadania e democracia", subtopics: ["Grécia Antiga", "Roma Antiga", "Democracia Ateniense"] },
      { name: "Idade Média", slug: "idade-media", description: "Feudalismo, Igreja e sociedade estamental", subtopics: ["Feudalismo", "Igreja Medieval", "Cruzadas", "Peste Negra"] },
      { name: "Idade Moderna", slug: "idade-moderna", description: "Renascimento, Reformas e Absolutismo", subtopics: ["Renascimento", "Reforma Protestante", "Absolutismo", "Mercantilismo"] },
      { name: "Brasil Colônia", slug: "brasil-colonia", description: "Colonização, economia e sociedade colonial", subtopics: ["Expansão Marítima", "Economia Colonial", "Escravidão", "Revoltas Coloniais"] },
      { name: "Brasil Império", slug: "brasil-imperio", description: "Independência, Segundo Reinado e Abolição", subtopics: ["Independência", "Período Regencial", "Segundo Reinado", "Abolição"] },
      { name: "Idade Contemporânea", slug: "idade-contemporanea", description: "Revoluções, industrialização e cidadania", subtopics: ["Revolução Francesa", "Revolução Industrial", "Imperialismo"] },
      { name: "Século XX", slug: "seculo-xx", description: "Guerras Mundiais, Guerra Fria e redemocratização", subtopics: ["1ª Guerra Mundial", "2ª Guerra Mundial", "Guerra Fria", "Ditadura Militar no Brasil", "Redemocratização"] },
    ],
    videos: [
      { title: "Brasil Colônia - Resumo Completo", channel: "Descomplica", duration: "45:00", url: "https://youtube.com" },
      { title: "Revolução Francesa ENEM", channel: "Stoodi", duration: "35:00", url: "https://youtube.com" },
      { title: "Ditadura Militar no Brasil", channel: "Descomplica", duration: "50:00", url: "https://youtube.com" },
      { title: "Segunda Guerra Mundial Completa", channel: "Me Salva!", duration: "1:00:00", url: "https://youtube.com" },
      { title: "História do Brasil - Resumão", channel: "Stoodi", duration: "2:00:00", url: "https://youtube.com" },
      { title: "Idade Média para ENEM", channel: "Descomplica", duration: "40:00", url: "https://youtube.com" },
      { title: "Era Vargas - Tudo que Cai", channel: "Stoodi", duration: "38:00", url: "https://youtube.com" },
      { title: "Revolução Industrial", channel: "Me Salva!", duration: "30:00", url: "https://youtube.com" },
      { title: "Imperialismo e Neocolonialismo", channel: "Descomplica", duration: "28:00", url: "https://youtube.com" },
      { title: "Guerra Fria Completa", channel: "Stoodi", duration: "42:00", url: "https://youtube.com" },
    ],
  },
  // Geografia
  {
    name: "Geografia",
    slug: "geografia",
    color: "#26A69A",
    icon: "Globe",
    area: "humanas",
    order: 7,
    topics: [
      { name: "Geografia Econômica", slug: "geografia-economica", description: "Globalização, indústria e comércio", subtopics: ["Globalização", "Indústria 4.0", "Comércio Internacional"] },
      { name: "Geografia Urbana e Demografia", slug: "urbana-demografia", description: "Urbanização, problemas urbanos e população", subtopics: ["Urbanização", "Problemas Urbanos", "Transição Demográfica"] },
      { name: "Geografia Física", slug: "geografia-fisica", description: "Relevo, clima, vegetação e solos", subtopics: ["Geologia", "Relevo", "Vegetação", "Solos"] },
      { name: "Hidrografia e Climatologia", slug: "hidrografia-climatologia", description: "Bacias hidrográficas, climas e fenômenos", subtopics: ["Bacias Hidrográficas", "Aquíferos", "Fenômenos Climáticos", "Massas de Ar"] },
      { name: "Geopolítica", slug: "geopolitica", description: "Conflitos, poder e relações internacionais", subtopics: ["Guerra Fria", "Conflitos Atuais", "Organizações Internacionais", "Energia"] },
      { name: "Geografia Agrária", slug: "geografia-agraria", description: "Agronegócio, reforma agrária e conflitos", subtopics: ["Agronegócio", "Agricultura Familiar", "Reforma Agrária", "MST"] },
      { name: "Meio Ambiente", slug: "meio-ambiente", description: "Impactos ambientais e sustentabilidade", subtopics: ["Desmatamento", "Aquecimento Global", "Poluição", "Sustentabilidade"] },
    ],
    videos: [
      { title: "Geopolítica Mundial Completa", channel: "Descomplica", duration: "50:00", url: "https://youtube.com" },
      { title: "Urbanização Brasileira ENEM", channel: "Stoodi", duration: "35:00", url: "https://youtube.com" },
      { title: "Climatologia para ENEM", channel: "Me Salva!", duration: "40:00", url: "https://youtube.com" },
      { title: "Globalização e Comércio", channel: "Descomplica", duration: "30:00", url: "https://youtube.com" },
      { title: "Meio Ambiente no ENEM", channel: "Stoodi", duration: "45:00", url: "https://youtube.com" },
      { title: "Relevo Brasileiro", channel: "Me Salva!", duration: "25:00", url: "https://youtube.com" },
      { title: "Hidrografia do Brasil", channel: "Descomplica", duration: "30:00", url: "https://youtube.com" },
      { title: "Questão Agrária no Brasil", channel: "Stoodi", duration: "38:00", url: "https://youtube.com" },
      { title: "Geopolítica - Conflitos Atuais", channel: "Me Salva!", duration: "42:00", url: "https://youtube.com" },
      { title: "Demografia ENEM", channel: "Descomplica", duration: "28:00", url: "https://youtube.com" },
    ],
  },
  // Filosofia
  {
    name: "Filosofia",
    slug: "filosofia",
    color: "#AB47BC",
    icon: "Brain",
    area: "humanas",
    order: 8,
    topics: [
      { name: "Filosofia Pré-Socrática", slug: "pre-socratica", description: "Origem da filosofia e os primeiros pensadores", subtopics: ["Tales de Mileto", "Heráclito", "Parmênides", "Pitágoras"] },
      { name: "Filósofos Clássicos", slug: "classicos", description: "Sócrates, Platão e Aristóteles", subtopics: ["Sócrates", "Platão", "Aristóteles"] },
      { name: "Helenismo", slug: "helenismo", description: "Estoicismo, epicurismo e ceticismo", subtopics: ["Estoicismo", "Epicurismo", "Ceticismo"] },
      { name: "Filosofia Medieval", slug: "medieval", description: "Patrística, escolástica, fé e razão", subtopics: ["Santo Agostinho", "São Tomás de Aquino", "Fé e Razão"] },
      { name: "Filosofia Política", slug: "politica", description: "Maquiavel, contratualistas e poder", subtopics: ["Maquiavel", "Hobbes", "Locke", "Rousseau"] },
      { name: "Filosofia Moderna", slug: "moderna", description: "Racionalismo, empirismo e Kant", subtopics: ["Descartes", "Empirismo", "Kant", "Iluminismo"] },
      { name: "Filosofia Contemporânea", slug: "contemporanea", description: "Escola de Frankfurt, existencialismo e pós-modernidade", subtopics: ["Escola de Frankfurt", "Existencialismo", "Nietzsche", "Foucault"] },
    ],
    videos: [
      { title: "Filosofia para ENEM - Completo", channel: "Descomplica", duration: "2:00:00", url: "https://youtube.com" },
      { title: "Sócrates, Platão e Aristóteles", channel: "Stoodi", duration: "45:00", url: "https://youtube.com" },
      { title: "Contratualistas - Hobbes, Locke, Rousseau", channel: "Me Salva!", duration: "40:00", url: "https://youtube.com" },
      { title: "Kant e o Criticismo", channel: "Descomplica", duration: "30:00", url: "https://youtube.com" },
      { title: "Escola de Frankfurt ENEM", channel: "Stoodi", duration: "35:00", url: "https://youtube.com" },
      { title: "Existencialismo de Sartre", channel: "Me Salva!", duration: "25:00", url: "https://youtube.com" },
      { title: "Maquiavel - O Príncipe", channel: "Descomplica", duration: "28:00", url: "https://youtube.com" },
      { title: "Ética e Moral - Conceitos", channel: "Stoodi", duration: "20:00", url: "https://youtube.com" },
      { title: "Nietzsche para ENEM", channel: "Me Salva!", duration: "30:00", url: "https://youtube.com" },
      { title: "Foucault e Relações de Poder", channel: "Descomplica", duration: "32:00", url: "https://youtube.com" },
    ],
  },
  // Sociologia
  {
    name: "Sociologia",
    slug: "sociologia",
    color: "#EF5350",
    icon: "Users",
    area: "humanas",
    order: 9,
    topics: [
      { name: "Sociólogos Clássicos", slug: "classicos", description: "Comte, Durkheim, Weber e Marx", subtopics: ["Auguste Comte", "Émile Durkheim", "Max Weber", "Karl Marx"] },
      { name: "Sociologia do Trabalho", slug: "trabalho", description: "Fordismo, toyotismo e uberização", subtopics: ["Fordismo", "Toyotismo", "Precarização", "Uberização"] },
      { name: "Sociologia Política", slug: "politica", description: "Estado, democracia e cidadania", subtopics: ["Formas de Governo", "Democracia", "Direitos Civis e Políticos"] },
      { name: "Cultura e Identidade", slug: "cultura", description: "Etnocentrismo, relativismo e alteridade", subtopics: ["Etnocentrismo", "Relativismo Cultural", "Alteridade", "Globalização Cultural"] },
      { name: "Movimentos Sociais", slug: "movimentos-sociais", description: "Lutas coletivas e participação popular", subtopics: ["Movimentos Clássicos", "Feminismo", "Movimento Negro", "LGBTQIA+"] },
      { name: "Indústria Cultural", slug: "industria-cultural", description: "Mídia, consumo e manipulação", subtopics: ["Escola de Frankfurt", "Cultura de Massa", "Redes Sociais"] },
      { name: "Sociologia Brasileira", slug: "brasileira", description: "Formação social, racismo e desigualdade", subtopics: ["Gilberto Freyre", "Sérgio Buarque", "Florestan Fernandes", "Racismo Estrutural"] },
    ],
    videos: [
      { title: "Sociologia para ENEM - Completo", channel: "Descomplica", duration: "1:45:00", url: "https://youtube.com" },
      { title: "Durkheim, Weber e Marx", channel: "Stoodi", duration: "50:00", url: "https://youtube.com" },
      { title: "Cultura e Identidade ENEM", channel: "Me Salva!", duration: "30:00", url: "https://youtube.com" },
      { title: "Movimentos Sociais no Brasil", channel: "Descomplica", duration: "35:00", url: "https://youtube.com" },
      { title: "Indústria Cultural - Adorno e Horkheimer", channel: "Stoodi", duration: "28:00", url: "https://youtube.com" },
      { title: "Sociologia do Trabalho ENEM", channel: "Me Salva!", duration: "32:00", url: "https://youtube.com" },
      { title: "Racismo Estrutural no Brasil", channel: "Descomplica", duration: "25:00", url: "https://youtube.com" },
      { title: "Democracia e Cidadania", channel: "Stoodi", duration: "30:00", url: "https://youtube.com" },
      { title: "Gilberto Freyre e Casa-Grande", channel: "Me Salva!", duration: "22:00", url: "https://youtube.com" },
      { title: "Questão Social no Brasil", channel: "Descomplica", duration: "35:00", url: "https://youtube.com" },
    ],
  },
  // Inglês
  {
    name: "Língua Inglesa",
    slug: "ingles",
    color: "#42A5F5",
    icon: "Languages",
    area: "linguagens",
    order: 10,
    topics: [
      { name: "Reading Comprehension", slug: "reading", description: "Estratégias de leitura e interpretação", subtopics: ["Skimming", "Scanning", "Inferência", "Cognatos"] },
      { name: "Grammar Essentials", slug: "grammar", description: "Tempos verbais e estruturas gramaticais", subtopics: ["Present Tenses", "Past Tenses", "Modal Verbs", "Conditionals"] },
      { name: "Vocabulary", slug: "vocabulary", description: "Vocabulário contextualizado", subtopics: ["False Cognates", "Phrasal Verbs", "Connectors"] },
    ],
    videos: [
      { title: "Inglês ENEM - Interpretação de Textos", channel: "Descomplica", duration: "40:00", url: "https://youtube.com" },
      { title: "Dicas de Inglês para ENEM", channel: "Stoodi", duration: "30:00", url: "https://youtube.com" },
      { title: "Tempos Verbais em Inglês", channel: "Me Salva!", duration: "35:00", url: "https://youtube.com" },
    ],
  },
  // Redação
  {
    name: "Redação",
    slug: "redacao",
    color: "#FF7043",
    icon: "PenTool",
    area: "linguagens",
    order: 11,
    topics: [
      { name: "Estrutura da Redação ENEM", slug: "estrutura", description: "Introdução, desenvolvimento e conclusão", subtopics: ["Tese", "Argumentação", "Proposta de Intervenção"] },
      { name: "Competências do ENEM", slug: "competencias", description: "As 5 competências avaliadas", subtopics: ["Competência 1: Norma Culta", "Competência 2: Tema", "Competência 3: Argumentação", "Competência 4: Coesão", "Competência 5: Proposta"] },
      { name: "Repertório Sociocultural", slug: "repertorio", description: "Referências e citações para a redação", subtopics: ["Filósofos", "Sociólogos", "Dados e Estatísticas", "Obras Literárias"] },
      { name: "Temas Recorrentes", slug: "temas", description: "Principais temas da redação ENEM", subtopics: ["Saúde Pública", "Educação", "Tecnologia", "Meio Ambiente", "Direitos Humanos"] },
    ],
    videos: [
      { title: "Redação Nota 1000 ENEM", channel: "Descomplica", duration: "1:00:00", url: "https://youtube.com" },
      { title: "Como fazer a Proposta de Intervenção", channel: "Professor Noslen", duration: "25:00", url: "https://youtube.com" },
      { title: "Repertório para Redação ENEM", channel: "Stoodi", duration: "40:00", url: "https://youtube.com" },
      { title: "Estrutura Dissertativa-Argumentativa", channel: "Me Salva!", duration: "30:00", url: "https://youtube.com" },
      { title: "Erros Comuns na Redação", channel: "Professor Noslen", duration: "20:00", url: "https://youtube.com" },
    ],
  },
];

export const achievementsData = [
  { name: "Primeira Questão", description: "Respondeu sua primeira questão", icon: "Star", category: "study", rarity: "common", xpReward: 50, condition: '{"type":"questions_answered","count":1}' },
  { name: "Foco Total", description: "Estudou por 1 hora seguida", icon: "Clock", category: "study", rarity: "common", xpReward: 75, condition: '{"type":"study_time","minutes":60}' },
  { name: "Streak Iniciante", description: "3 dias consecutivos estudando", icon: "Flame", category: "streak", rarity: "common", xpReward: 100, condition: '{"type":"streak","days":3}' },
  { name: "Semana Perfeita", description: "7 dias consecutivos estudando", icon: "Flame", category: "streak", rarity: "rare", xpReward: 250, condition: '{"type":"streak","days":7}' },
  { name: "Mês de Ferro", description: "30 dias consecutivos estudando", icon: "Shield", category: "streak", rarity: "legendary", xpReward: 1000, condition: '{"type":"streak","days":30}' },
  { name: "Dez em Dez", description: "10 questões corretas seguidas", icon: "Target", category: "study", rarity: "rare", xpReward: 200, condition: '{"type":"combo","count":10}' },
  { name: "Perfeccionista", description: "20 questões seguidas corretas", icon: "Target", category: "mastery", rarity: "epic", xpReward: 400, condition: '{"type":"combo","count":20}' },
  { name: "Explorador", description: "Estudou 5 matérias diferentes", icon: "BookOpen", category: "study", rarity: "common", xpReward: 100, condition: '{"type":"subjects_studied","count":5}' },
  { name: "Enciclopédia", description: "Estudou todas as matérias em uma semana", icon: "Brain", category: "study", rarity: "epic", xpReward: 400, condition: '{"type":"all_subjects_week"}' },
  { name: "Centenário", description: "100 questões respondidas", icon: "Award", category: "study", rarity: "rare", xpReward: 300, condition: '{"type":"questions_answered","count":100}' },
  { name: "Mil Questões", description: "1000 questões respondidas", icon: "Sparkles", category: "study", rarity: "legendary", xpReward: 1500, condition: '{"type":"questions_answered","count":1000}' },
  { name: "Maratonista", description: "100 questões em um único dia", icon: "Rocket", category: "study", rarity: "epic", xpReward: 500, condition: '{"type":"daily_questions","count":100}' },
  { name: "Madrugador", description: "Estudou antes das 6h", icon: "Sun", category: "special", rarity: "rare", xpReward: 150, condition: '{"type":"time_of_day","before":6}' },
  { name: "Noturno", description: "Estudou após meia-noite", icon: "Moon", category: "special", rarity: "rare", xpReward: 150, condition: '{"type":"time_of_day","after":0}' },
  { name: "ENEM Ready", description: "Completou um simulado completo", icon: "Trophy", category: "study", rarity: "epic", xpReward: 600, condition: '{"type":"simulado_complete","count":1}' },
  { name: "Mestre da Matemática", description: "90%+ de acerto em Matemática", icon: "Crown", category: "mastery", rarity: "epic", xpReward: 500, condition: '{"type":"subject_mastery","subject":"matematica","min":90}' },
  { name: "Mestre da Física", description: "90%+ de acerto em Física", icon: "Crown", category: "mastery", rarity: "epic", xpReward: 500, condition: '{"type":"subject_mastery","subject":"fisica","min":90}' },
  { name: "Mestre da Química", description: "90%+ de acerto em Química", icon: "Crown", category: "mastery", rarity: "epic", xpReward: 500, condition: '{"type":"subject_mastery","subject":"quimica","min":90}' },
  { name: "Cientista", description: "90%+ em Física, Química e Biologia", icon: "Brain", category: "mastery", rarity: "legendary", xpReward: 1500, condition: '{"type":"area_mastery","area":"natureza","min":90}' },
  { name: "Humanista", description: "90%+ em todas as Humanas", icon: "BookOpen", category: "mastery", rarity: "legendary", xpReward: 1500, condition: '{"type":"area_mastery","area":"humanas","min":90}' },
  { name: "Polímata", description: "90%+ em todas as matérias", icon: "Crown", category: "mastery", rarity: "legendary", xpReward: 2000, condition: '{"type":"total_mastery","min":90}' },
  { name: "Boss Slayer", description: "Venceu 10 Boss Battles", icon: "Swords", category: "special", rarity: "epic", xpReward: 750, condition: '{"type":"boss_battles","count":10}' },
  { name: "Velocista", description: "20 questões corretas em 10 minutos", icon: "Zap", category: "special", rarity: "epic", xpReward: 500, condition: '{"type":"speed_challenge","questions":20,"minutes":10}' },
  { name: "Combo Master", description: "Combo de 20x em uma sessão", icon: "Flame", category: "study", rarity: "epic", xpReward: 400, condition: '{"type":"combo","count":20}' },
  { name: "Dedicação Total", description: "50 horas de estudo acumuladas", icon: "Heart", category: "study", rarity: "rare", xpReward: 300, condition: '{"type":"total_study_hours","hours":50}' },
  { name: "Visionário", description: "Completou 10 metas semanais", icon: "Eye", category: "special", rarity: "rare", xpReward: 250, condition: '{"type":"weekly_goals","count":10}' },
  { name: "Trilha Completa", description: "Completou todos os tópicos de uma matéria", icon: "Award", category: "mastery", rarity: "epic", xpReward: 600, condition: '{"type":"subject_complete"}' },
  { name: "Estuda Rápido", description: "50 questões fáceis sem erro", icon: "Zap", category: "study", rarity: "rare", xpReward: 200, condition: '{"type":"easy_streak","count":50}' },
  { name: "Desafiante", description: "50 questões difíceis respondidas", icon: "Swords", category: "study", rarity: "epic", xpReward: 400, condition: '{"type":"hard_questions","count":50}' },
  { name: "Primeiro Simulado", description: "Completou seu primeiro simulado", icon: "Clock", category: "study", rarity: "common", xpReward: 100, condition: '{"type":"simulado_complete","count":1}' },
  { name: "Lenda Viva", description: "Desbloqueou 25 conquistas", icon: "Sparkles", category: "special", rarity: "legendary", xpReward: 3000, condition: '{"type":"achievements_unlocked","count":25}' },
  { name: "Mestre Supremo", description: "Alcançou nível Lenda", icon: "Crown", category: "mastery", rarity: "legendary", xpReward: 5000, condition: '{"type":"level","min":12}' },
];

export const mockUsersData = [
  { name: "Maria Silva", email: "maria@example.com", xp: 15420, level: 12, streak: 45 },
  { name: "João Santos", email: "joao@example.com", xp: 12890, level: 11, streak: 32 },
  { name: "Ana Costa", email: "ana@example.com", xp: 11200, level: 10, streak: 28 },
  { name: "Pedro Oliveira", email: "pedro@example.com", xp: 9800, level: 9, streak: 15 },
  { name: "Lucas Ferreira", email: "lucas@example.com", xp: 8500, level: 8, streak: 20 },
];
